#define BASE_SPEED 50
#define CORNER_SPEED 45
#define MIN_SPEED 30
#define MAX_SPEED 100
#define DEBUG_MODE false

#define SENSOR_COUNT 11
#define SENSOR_CALIBRATION_READING_COUNT 3
#define SENSOR_TRESHOLD_OFFSET 0.2
#define DERIVATIVE_FILTER_RATIO 0.5

#define LEFT_CENTER_TRESHOLD 16
#define RIGHT_CENTER_TRESHOLD 96

#define BRAKE_TIME_MILISECONDS 20

#define KP 22.4
#define KD 0.751

#define LOGGING false
#define SAMPLE_RATE_HZ 100
#define MAX_SAMPLES 8000